import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import {ClerkProvider,SignedIn,SignedOut,SignIn} from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground`}>
        <ClerkProvider>
          <SignedOut>
            <div className="min-w-screen min-h-screen flex justify-center items-center h-screen bg-background">
              <SignIn
                routing="hash"
                appearance={{
                  variables: {
                    colorPrimary: "#6366f1",
                    colorBackground: "#18181b",
                    colorText: "#f4f4f5",
                    colorInputBackground: "#27272a",
                    colorInputText: "#f4f4f5",
                    borderRadius: "0.75rem",
                    fontFamily: "inherit",
                  },
                  elements: {
                    card: "shadow-none border border-border bg-card",
                    formButtonPrimary: "bg-primary text-primary-foreground hover:bg-primary/90",
                    headerTitle: "text-2xl font-bold",
                    headerSubtitle: "text-muted-foreground",
                    socialButtonsBlockButton: "bg-muted text-foreground hover:bg-muted/80",
                    footerAction: "text-muted-foreground",
                  },
                }}
              />
            </div>
          </SignedOut>
          <SignedIn>
            {children}
          </SignedIn>
        </ClerkProvider>
      </body>
    </html>
  );
}
